### PR TITLE
Update to v0.7.1

### PR DESCRIPTION
**Pull request by cachitas**

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.4.0 to fix the AppVeyor CI failure.

**Comment by jakirkham** [comment]
Also would recommend waiting for the CI results before merging in the future lest problems with the build be missed.

**Comment by cachitas** [comment]
@jakirkham is it possible to re-render without `conda` installed?
Where can I find instructions to `python setup.py install` `conda-smithy` and proceed from there?

**Comment by cachitas** [comment]
This was painful...

I managed installing all dependencies manually by cloning conda repos and `python setup.py install`. The versions that worked for me were:

```
conda-build (2.1.17)        <-- NEWER VERSIONS DO NOT WORK
conda-build-all (1.1.1)
conda-smithy (2.4.0)
conda-verify (2.0.0)
```

**Comment by jakirkham** [comment]
😕 Why not use `conda` to install everything?

**Comment by cachitas** [comment]
I don't have `conda` installed. Not an avid user. Nevertheless I have to distribute a package to Anaconda users, hence using this feedstock.

I may have over-complicated the process here, but I am happy it was possible to rerender the feedstock :smile: 

By the way, I understand `conda-smith` is not targetet at `pip` users, but I think it is missing a dependency on `pyyaml`. At least I had to manually `pip install` it.

**Comment by jakirkham** [comment]
Well all the tooling here depends on one having at least Miniconda installed somewhere and then `conda` installing everything in that. The basic stack doesn't take up that much space. So would recommend having it installed somewhere (even if you don't use it regularly).

I suppose we could have a Docker container for this sort of thing. Have thought about it occasionally. Though have to admit that sounds like too much. Not sure if that actually makes anything easier.

Yeah `conda-smithy` lists basically no requirements in `setup.py`. They are all in the `conda` recipe. So trying to `pip install` it and then add all the dependencies would not likely be pleasant. The problem is that things like `conda` and `conda-build` have historically not been available on PyPI, or were incredibly outdated and often the PyPI packages were somehow limited. Not to mention we haven't placed any of our own dependencies on PyPI.

All of this to say, glad that you were able to make it work. Though would recommend using Miniconda for this sort of task in the future.

**Pull request merged**
